# Generated by Django 5.2.4 on 2025-08-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
